### ISSUE TITLE
Minor modifications in the dataset

### ISSUE THREAD

**Issue by jenlindadsouza** [umanlp/tg2019task#1]
Would like to confirm the following minor findings in the dataset:

1) The WorldTree corpus (Jansen et al., 2018) describes four coarse classes of explanation sentence roles, however the shared task dataset shows two additional, viz. Role (2.9%) and Neg (0.8%);
2) At QuestionID ‘Ex1_SC_LBS10789’, for the answer explanation sentences 1868-9bad-b9cc-1302|NE, af66-465f-0191-efbd|NE, 499d-e50e-b35d-35c2|NE, and dd90-d920-81f6-416c|NE, we can assume the coarse class type 'NE' as 'NEG'?; and
3) Could not find explanation with ID 5124-b03e-ff20-b4d6 in the table stores.

Thank you very much for your help and for organizing the shared task!

**Comment by PeterAJansen** [comment]
Thanks for the question, and apologies for taking a few days to get back to you.

The short answer is that the data quality is generally very good, but it's living data (there are annotators actively working on expanding it) and so sometimes small items slip through the cracks.  The missing row (in 3) and roles (1 and 2) are errors, but shouldn't affect the scoring of the shared task in a meaningful way (accurately predicting roles isn't required for the task, but this is certainly super useful information included in the annotation that should help, if your algorithm is able to make use of it). 

The slightly longer answer is: We weren't sure how many roles we would identify ahead of time in the data before annotation, and so we made a handful of annotation, identified the core ones (central, grounding, and the lexical glue/bridging facts), then through the course of annotation noted a few others (e.g. extra background information and negative examples were somewhat common).  Negative roles were when the multiple-choice question tends to require a 'solve by elimination' problem solving scheme,  and we decided after a short while to focus on the questions that didn't require explicit "multiple choice machinery" to solve, but that were normal free-form questions that just happened to be presented as multiple-choice questions.  In that case we stopped including the NEG role tag.  The background tag was included for information that was extra background information, but strictly speaking not required to answer the question -- but we stopped including this because it was a little challenging for the annotators.  The "ROLE" tag signifies that the annotators had difficulty determining which category the information belonged in, and so didn't make a decision (this was sometimes the case, primarily between central/grounding).   

Please let us know if you have any additional questions or run into any issues!
